### ISSUE TITLE
MultiSig::Sign feature does not seem to work

### ISSUE THREAD

**Issue by DenisCarriere** [eostoolkit/eostoolkit#62]
Been trying out the SingleSig & MultiSig mode.

Here's a very easy example that I'm trying to accomplish .

**Transaction:**

```json
[
  {
    "account": "eosio.token",
    "name": "transfer",
    "data": {
      "from": "deniscarrier",
      "to": "eosnationexp",
      "memo": "",
      "quantity": "0.0001 EOS"
    }
  }
]
```

Using `deniscarrier@active` as the authority

![image](https://user-images.githubusercontent.com/550895/44278260-6f4e0180-a21b-11e8-9618-28818df7ae53.png)

This section works

[tx-deniscarrier-1534524354987.json.zip](https://github.com/eostoolkit/eostoolkit/files/2298045/tx-deniscarrier-1534524354987.json.zip)

![image](https://user-images.githubusercontent.com/550895/44278292-8d1b6680-a21b-11e8-8ad9-e4d63fb88e08.png)

When I go to `sign` the transaction:

```json
{
  "expiration": "2018-08-17T17:45:54",
  "ref_block_num": 23856,
  "ref_block_prefix": 1460912772,
  "net_usage_words": 0,
  "max_cpu_usage_ms": 0,
  "delay_sec": 0,
  "context_free_actions": [],
  "actions": [
    {
      "account": "eosio.token",
      "name": "transfer",
      "authorization": [
        {
          "actor": "deniscarrier",
          "permission": "active"
        }
      ],
      "data": "7095bbd720eca64a50bb9ad465333155010000000000000004454f530000000000"
    }
  ],
  "transaction_extensions": []
}
```

The transaction fails

![image](https://user-images.githubusercontent.com/550895/44278364-c6ec6d00-a21b-11e8-8c58-3fc09691a131.png)

Console: Error message

```
code: 402
isError: true
message: "User rejected the signature request"
type : "signature_rejected"
```

The issue seems to be coming from somewhere in the `signTransaction` try/catch statement:

https://github.com/eostoolkit/eostoolkit/blob/6e90656286e7d9c6b77474bd8d6fad268f311a4e/app/containers/OfflineClient/saga.js

**containers/OfflineClient/saga.js**
```js
export function* signTransaction(action) {
  yield put(loadingNotification());
  try {
    const networkReader = yield select(makeSelectReader());
    const signer = yield select(makeSelectSigner());
    const identity = yield select(makeSelectIdentity());
    const network = yield select(makeSelectActiveNetwork());

    if(!networkReader || !signer || !identity) {
      throw { message: 'Require network connection and identity'}
    }

    //sign a transaction json
    const chainId = network.network.chainId;
    const transaction = JSON.parse(action.data.transaction);
    const chainIdBuf = Buffer.from(chainId,'hex');
    const packedContextFreeData = Buffer.from(new Uint8Array(32)) // TODO
    let buf = networkReader.fc.toBuffer('transaction',transaction);
    let signBuf = Buffer.concat([chainIdBuf, buf, packedContextFreeData]);
    let signature = yield signer.getArbitrarySignature(identity.publicKey,signBuf,'Offline signing of multisig action',false);


    const data = JSON.stringify(signature, null, 2);
    const filename = `signature-${identity.name}-${(new Date()).getTime()}.json`;

    fileDownload(data,filename,'application/json');
    yield put(successNotification(signature));

  } catch (err) {
    console.error('An EOSToolkit error occured - see details below:');
    console.error(err);
    yield put(failureNotification(err));
  }
}
```

**Comment by DenisCarriere** [comment]
✅ Resolved: The issue was I wasn't using Scatter Desktop for the MultiSig mode:

Fixed using the latest version of Scatter Desktop v8.6.0

https://github.com/GetScatter/ScatterDesktop/releases

![image](https://user-images.githubusercontent.com/550895/44301008-36c32c00-a2de-11e8-8e62-cd2cb9e6193c.png)

**Comment by micalways** [comment]
Hi, after changing owner and active key due fairy wallet I now can’t intteract with scatter:
code: 402
isError: true
message: "User rejected the signature request"
type : "signature_rejected"
What can I do?
